import Head from "next/head";
import { getAllPosts } from "lib/notionAPI";
import SinglePost from "components/Post/SinglePost";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();
  return {
    props: {
      allPosts: allPosts,
    },
    revalidate: 60,
  };
};

export default function Home({ allPosts }) {
  console.log(allPosts);
  return (
    <div>
      <Head>
        <title>Atsushi-blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="style.css" href="/style.css/" />
      </Head>
      <main className="">
        <h1 className="title">Atsushi-blog🖥</h1>
        {allPosts.map((post) => (
          <div>
            <SinglePost
              icon={post.icon}
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
            />
          </div>
        ))}
      </main>
    </div>
  );
}
